Controllers/BaiVietController.cs
using ClothesShoping.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
namespace ClothesShoping.Controllers
{
    public class BaiVietController : Controller
    {
        private readonly ClothesShopingDbContext _context;
        private readonly HttpContext _httpContext = new HttpContextAccessor().HttpContext;

        public BaiVietController(ClothesShopingDbContext context)
        {
            _context = context;
        }

        // GET: Index 
        public IActionResult Index(int? trang)
        {
            var danhSach = LayDanhSachBaiViet(trang ?? 1);
            if (danhSach.BaiViet.Count == 0)
                return NotFound();
            else
                return View(danhSach);
        }

        private PhanTrangBaiViet LayDanhSachBaiViet(int trangHienTai)
        {
            int maxRows = 12;

            PhanTrangBaiViet phanTrang = new PhanTrangBaiViet();
            phanTrang.BaiViet = _context.BaiViet
                .Include(s => s.NguoiDung)
                .Include(s => s.ChuDe)
                .Where(r => r.KiemDuyet == true && r.HienThi == true)
                .OrderByDescending(r => r.NgayDang)
                .Skip((trangHienTai - 1) * maxRows)
                .Take(maxRows).ToList();

            decimal tongSoTrang = Convert.ToDecimal(_context.BaiViet.Count()) / Convert.ToDecimal(maxRows);
            phanTrang.TongSoTrang = (int)Math.Ceiling(tongSoTrang);
            phanTrang.TrangHienTai = trangHienTai;

            return phanTrang;
        }

        // GET: ChuDe 
        public IActionResult ChuDe(string tenChuDe, int? trang)
        {
            var danhSachPhanLoai = LayDanhSachBaiVietTheoChuDe(tenChuDe, trang ?? 1);
            if (danhSachPhanLoai.BaiViet.Count == 0)
                return NotFound();
            else
                return View(danhSachPhanLoai);


        }

        private PhanTrangBaiViet LayDanhSachBaiVietTheoChuDe(string tenChuDe, int trangHienTai)
        {
            int maxRows = 12;

            var baiVietTheoChuDe = _context.BaiViet
                .Include(s => s.NguoiDung)
                .Include(s => s.ChuDe)
                .Where(r => r.KiemDuyet == true && r.HienThi == true && r.ChuDe.TenChuDeKhongDau == tenChuDe);

            PhanTrangBaiViet phanTrang = new PhanTrangBaiViet();
            phanTrang.BaiViet = baiVietTheoChuDe.OrderByDescending(r => r.NgayDang)
                .Skip((trangHienTai - 1) * maxRows)
                .Take(maxRows).ToList();

            decimal tongSoTrang = Convert.ToDecimal(baiVietTheoChuDe.Count()) / Convert.ToDecimal(maxRows);
            phanTrang.TongSoTrang = (int)Math.Ceiling(tongSoTrang);
            phanTrang.TrangHienTai = trangHienTai;

            return phanTrang;
        }

        // GET: ChiTiet 
        public IActionResult ChiTiet(string tenChuDe, string tieuDe)
        {
            var baiViet = _context.BaiViet
                .Include(s => s.NguoiDung)
                .Include(s => s.ChuDe)
                .Include(s => s.BinhLuanBaiViet)
                .Where(r => r.KiemDuyet == true && r.HienThi == true && r.TieuDeKhongDau == tieuDe).SingleOrDefault();
            if (baiViet == null)
                return NotFound();
            else
            {
                // Xử lý tăng lượt xem 
                string _sessionKey = "DaXemBaiViet_" + baiViet.ID;

                if (string.IsNullOrEmpty(_httpContext.Session.GetString(_sessionKey)))
                {
                    baiViet.LuotXem = baiViet.LuotXem + 1;
                    _context.Update(baiViet);
                    _context.SaveChanges();

                    _httpContext.Session.SetString(_sessionKey, "1");
                }



                // Lấy bài viết cùng chuyên mục 
                var baiVietCungChuyenMuc = _context.BaiViet
                    .Include(s => s.NguoiDung)
                    .Include(s => s.ChuDe)
                    .Where(r => r.KiemDuyet == true && r.HienThi == true && r.ChuDeID == baiViet.ChuDeID && r.ID != baiViet.ID)
                    .OrderByDescending(r => r.NgayDang)
                    .Take(4);
                ViewData["BaiVietCungChuyenMuc"] = baiVietCungChuyenMuc;

                return View(baiViet);
            }
        }
    }
}

Controllers/KhachHangController.cs
using ClothesShoping.Logic;
using ClothesShoping.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq.Dynamic.Core;
using BC = BCrypt.Net.BCrypt;

namespace ClothesShoping.Controllers
{
    [Authorize(Roles = "Admin, User")]
    public class KhachHangController : Controller
    {
        private readonly ClothesShopingDbContext _context;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly IMailLogic _mailLogic;

        public KhachHangController(ClothesShopingDbContext context, IHttpContextAccessor httpContextAccessor, IMailLogic mailLogic)
        {
            _context = context;
            _httpContextAccessor = httpContextAccessor;
            _mailLogic = mailLogic;
        }

        public IActionResult Index(string? successMessage)
        {
            int maNguoiDung = Convert.ToInt32(_httpContextAccessor.HttpContext.User.Claims.FirstOrDefault(c => c.Type == "ID")?.Value);
            var nguoiDung = _context.NguoiDung
                .Where(r => r.ID == maNguoiDung)
                .Include(s => s.DatHang)
                .SingleOrDefault();

            if (nguoiDung == null)
                return NotFound();

            int soLuongDonHang = nguoiDung.DatHang.Count();
            TempData["SoLuongDonHang"] = soLuongDonHang;
            if (!string.IsNullOrEmpty(successMessage))
                TempData["ThongBao"] = successMessage;

            return View(new NguoiDung_ChinhSua(nguoiDung));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CapNhatHoSo(int id, [Bind("ID,HoVaTen,Email,DienThoai,DiaChi,TenDangNhap,MatKhau,XacNhanMatKhau")] NguoiDung_ChinhSua nguoiDung)
        {
            if (id != nguoiDung.ID)
                return NotFound();

            if (ModelState.IsValid)
            {
                try
                {
                    var n = await _context.NguoiDung.FindAsync(id);

                    if (nguoiDung.MatKhau == null)
                    {
                        n.HoVaTen = nguoiDung.HoVaTen;
                        n.DienThoai = nguoiDung.DienThoai;
                        n.DiaChi = nguoiDung.DiaChi;
                    }
                    else
                    {
                        n.MatKhau = BC.HashPassword(nguoiDung.MatKhau);
                        n.XacNhanMatKhau = BC.HashPassword(nguoiDung.MatKhau);
                    }

                    _context.Update(n);
                    await _context.SaveChangesAsync();
                }
                catch (Exception ex)
                {
                    throw new Exception(ex.Message.ToString());
                }

                return RedirectToAction("Index", new { successMessage = "Đã cập nhật thông tin thành công." });
            }

            return View("Index", nguoiDung);
        }

        public IActionResult DatHang()
        {
            var gioHangLogic = new GioHangLogic(_context);
            var gioHang = gioHangLogic.LayGioHang();
            TempData["TongTien"] = gioHangLogic.LayTongTienSanPham();

            return View(gioHang);
        }

        [HttpPost]
        public async Task<IActionResult> DatHang(DatHang datHang)
        {
            var gioHangLogic = new GioHangLogic(_context);
            var gioHang = gioHangLogic.LayGioHang();

            if (string.IsNullOrWhiteSpace(datHang.DienThoaiGiaoHang) || string.IsNullOrWhiteSpace(datHang.DiaChiGiaoHang))
            {
                TempData["TongTien"] = gioHangLogic.LayTongTienSanPham();
                TempData["ThongBaoLoi"] = "Thông tin giao hàng không được bỏ trống.";
                return View(gioHang);
            }

            try
            {
                var dh = new DatHang
                {
                    NguoiDungID = Convert.ToInt32(_httpContextAccessor.HttpContext.User.Claims.FirstOrDefault(c => c.Type == "ID")?.Value),
                    TinhTrangID = 1,
                    DienThoaiGiaoHang = datHang.DienThoaiGiaoHang,
                    DiaChiGiaoHang = datHang.DiaChiGiaoHang,
                    NgayDatHang = DateTime.Now
                };

                _context.DatHang.Add(dh);
                await _context.SaveChangesAsync();

                foreach (var item in gioHang)
                {
                    var ct = new DatHang_ChiTIet
                    {
                        DatHangID = dh.ID,
                        SanPhamID = item.SanPhamID,
                        SoLuong = Convert.ToInt16(item.SoLuongTrongGio),
                        DonGia = item.SanPham.DonGia
                    };
                    _context.DatHang_ChiTiet.Add(ct);
                    await _context.SaveChangesAsync();
                }

                var mailInfo = new MailInfo { Subject = "Đặt hàng thành công tại ClothesShop.Com.Vn" };
                var datHangInfo = _context.DatHang
                    .Where(r => r.ID == dh.ID)
                    .Include(s => s.NguoiDung)
                    .Include(s => s.DatHang_ChiTiet)
                    .SingleOrDefault();

                await _mailLogic.GoiEmailDatHangThanhCong(datHangInfo, mailInfo);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message.ToString());
            }

            return RedirectToAction("DatHangThanhCong");
        }

        public async Task<IActionResult> DonHangCuaToi()
        {
            int maNguoiDung = Convert.ToInt32(_httpContextAccessor.HttpContext.User.Claims.FirstOrDefault(c => c.Type == "ID")?.Value);
            var datHang = _context.DatHang
                .Where(r => r.NguoiDungID == maNguoiDung)
                .Include(d => d.NguoiDung)
                .Include(d => d.TinhTrang)
                .Include(d => d.DatHang_ChiTiet)
                .ThenInclude(s => s.SanPham);

            return View(await datHang.ToListAsync());
        }

        public IActionResult DatHangThanhCong()
        {
            var gioHangLogic = new GioHangLogic(_context);
            gioHangLogic.XoaTatCa();

            return View();
        }
    }
}

Controllers/LienHeController.cs
using Microsoft.AspNetCore.Mvc;
namespace ClothesShoping.Controllers
{
    public class LienHeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/SanPhamController.cs
using ClothesShoping.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using static ClothesShoping.Models.SanPham;

namespace ClothesShoping.Controllers
{
    public class SanPhamController : Controller
    {
        private readonly ClothesShopingDbContext _context;

        public SanPhamController(ClothesShopingDbContext context)
        {
            _context = context;
        }
        
        // GET: Index 
        public IActionResult Index(int? trang)
        {
            var danhSach = LayDanhSachSanPham(trang ?? 1);
            if (danhSach.SanPham.Count == 0)
                return NotFound();
            else
                return View(danhSach);
        }

        private PhanTrangSanPham LayDanhSachSanPham(int trangHienTai)
        {
            int maxRows = 20;

            PhanTrangSanPham phanTrang = new PhanTrangSanPham();
            phanTrang.SanPham = _context.SanPham
                .Include(s => s.HangSanXuat)
                .Include(s => s.LoaiSanPham)
                .OrderBy(r => r.LoaiSanPhamID)
                .Skip((trangHienTai - 1) * maxRows)
                .Take(maxRows).ToList();

            decimal tongSoTrang = Convert.ToDecimal(_context.SanPham.Count()) / Convert.ToDecimal(maxRows);
            phanTrang.TongSoTrang = (int)Math.Ceiling(tongSoTrang);
            phanTrang.TrangHienTai = trangHienTai;

            return phanTrang;
        }
        // GET: PhanLoai 
        public IActionResult PhanLoai(string tenLoai, int? trang)


        {
            var danhSachPhanLoai = LayDanhSachSanPhamTheoPhanLoai(tenLoai, trang ?? 1);
            if (danhSachPhanLoai.SanPham.Count == 0)
                return NotFound();
            else
                return View(danhSachPhanLoai);
        }

        private PhanTrangSanPham LayDanhSachSanPhamTheoPhanLoai(string tenLoai, int trangHienTai)
        {
            int maxRows = 20;

            var sanPhamPhanLoai = _context.SanPham
                .Include(s => s.HangSanXuat)
                .Include(s => s.LoaiSanPham)
                .Where(r => r.LoaiSanPham.TenLoaiKhongDau == tenLoai);

            PhanTrangSanPham phanTrang = new PhanTrangSanPham();
            phanTrang.SanPham = sanPhamPhanLoai.OrderBy(r => r.LoaiSanPhamID)
                .Skip((trangHienTai - 1) * maxRows)
                .Take(maxRows).ToList();

            decimal tongSoTrang = Convert.ToDecimal(sanPhamPhanLoai.Count()) / Convert.ToDecimal(maxRows);
            phanTrang.TongSoTrang = (int)Math.Ceiling(tongSoTrang);
            phanTrang.TrangHienTai = trangHienTai;

            return phanTrang;
        }
        public IActionResult ChiTiet(string tenLoai, string tenSanPham)
        {
            var sanPham = _context.SanPham
                .Include(s => s.HangSanXuat)
                .Include(s => s.LoaiSanPham)
                .Where(r => r.TenSanPhamKhongDau == tenSanPham).SingleOrDefault();
            if (sanPham == null)
                return NotFound();
            else
                return View(sanPham);
        }
        public IActionResult TimKiemSanPhamTheoTen(string tenSanPham,int trang =1)
        {
            int maxRows = 20;
             var sanPhams = _context.SanPham
                .Include(s => s.HangSanXuat)
                .Include(s => s.LoaiSanPham)
                .Where(s => s.TenSanPham.Contains(tenSanPham) || s.LoaiSanPham.TenLoai.Contains(tenSanPham)); 
            var phanTrang = new PhanTrangSanPham
            { 
                SanPham = sanPhams
                .OrderBy(r => r.TenSanPham)
                .Skip((trang - 1) * maxRows)
                .Take(maxRows).ToList(),
                TongSoTrang = (int)Math.Ceiling(sanPhams.Count() / (double)maxRows), 
                TrangHienTai = trang
            }; 
                ViewBag.SearchString = tenSanPham; 
                return View(phanTrang);
        }
    }
}

Views/Shared/_Layout.cshtml
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor _httpContextAccessor;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <!-- SEO Meta Tags -->
    <meta name="description" content="" />
    <meta name="keywords" content="" />
    <meta name="author" content="" />
    <!-- Viewport -->
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="theme-color" content="#ffffff" />
    <title>@ViewData["Title"] - ITShop</title>
    <!-- Favicon and Touch Icons -->


    <link rel="apple-touch-icon" sizes="180x180" href="~/img/apple-touch-icon.png" />
    <link rel="icon" type="image/png" sizes="32x32" href="~/img/favicon-32x32.png" />
    <link rel="icon" type="image/png" sizes="16x16" href="~/img/favicon-16x16.png" />

    <!-- CSS -->
    <link rel="stylesheet" media="screen" href="~/vendor/simplebar/simplebar.min.css" />
    <link rel="stylesheet" media="screen" href="~/vendor/tiny-slider/tiny-slider.css" />
    <link rel="stylesheet" media="screen" href="~/vendor/nouislider/nouislider.min.css" />
    <link rel="stylesheet" media="screen" href="~/vendor/drift-zoom/drift-basic.min.css" />
    <link rel="stylesheet" media="screen" href="~/vendor/lightgallery/lightgallery-bundle.min.css" />
    <link rel="stylesheet" media="screen" href="~/css/theme.min.css" />
    @await RenderSectionAsync("Styles", required: false)
</head>

<body class="handheld-toolbar-enabled">
    <main class="page-wrapper">
        <header class="shadow-sm">
            <div class="navbar-sticky bg-light">
                <div class="navbar navbar-expand-lg navbar-light">
                    <div class="container">
                        <a class="navbar-brand d-none d-sm-block flex-shrink-0" asp-area="" asp-controller="Home" asp-action="Index">
                            <img src="~/img/logo-dark.png" width="142" />
                        </a>
                        <a class="navbar-brand d-sm-none flex-shrink-0 me-2" asp-area="" asp-controller="Home" asp-action="Index">
                            <img src="~/img/logo-icon.png" width="74" />
                        </a>
                        <div class="input-group d-none d-lg-flex mx-4">
     <input class="form-control rounded-end pe-5" type="text" placeholder="Tìm kiếm" id="searchInput" />
    <a asp-area="" asp-controller="SanPham" asp-action="TimKiem" 
       asp-route-searchString="@ViewBag.SearchString" 
       class="ci-search position-absolute top-50 end-0 translate-middle-y text-muted fs-base me-3"
       onclick="submitSearch()">
    </a>                        
</div>

@section Scripts {
    <script type="text/javascript">
        function submitSearch() {
            var searchString = document.getElementById("searchInput").value;
            var url = '@Url.Action("TimKiem", "SanPham")' + '?searchString=' + encodeURIComponent(searchString);
            window.location.href = url;
        }
    </script>
}
                        <div class="navbar-toolbar d-flex flex-shrink-0 align-items-center">
                            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                                <span class="navbar-toggler-icon"></span>
                            </button>
                            <a class="navbar-tool navbar-stuck-toggler" href="#menu">
                                <span class="navbar-tool-tooltip">Mở rộng menu</span>
                                <div class="navbar-tool-icon-box"><i class="navbar-tool-icon ci-menu"></i></div>
                            </a>
                            @if (!_httpContextAccessor.HttpContext.User.Identity.IsAuthenticated)
                            {
                                <a class="navbar-tool ms-1 ms-lg-0 me-n1 me-lg-2" asp-area="" asp-controller="Home" asp-action="Login">
                                    <div class="navbar-tool-icon-box"><i class="navbar-tool-icon ci-user"></i></div>
                                    <div class="navbar-tool-text ms-n3"><small>Xin chào</small>Khách hàng</div>              
                                </a>
                            }
                            else
                            {
                                <a class="navbar-tool ms-1 ms-lg-0 me-n1 me-lg-2" asp-area="" asp-controller="KhachHang" asp-action="Index">
                                    <div class="navbar-tool-icon-box"><i class="navbar-tool-icon ci-user"></i></div>
                                    <div class="navbar-tool-text ms-n3">
                                        <small>Xin chào</small>
                                        @_httpContextAccessor.HttpContext.User.Claims.FirstOrDefault(c => c.Type == "HoVaTen")?.Value
                                    </div>
                                </a>
                            }
                            
                        </div>
                            <div class="navbar-tool ms-3">
                                <a class="navbar-tool-icon-box bg-secondary" asp-area="" asp-controller="GioHang" asp-action="Index">
                                    <span class="navbar-tool-label">1</span><i class="navbar-tool-icon ci-cart"></i>
                                </a>
                            <a class="navbar-tool-text" asp-area="" asp-controller="GioHang" asp-action="Index"><small>Giỏ hàng</small>0đ </a>
                        </div>
                        </div>
                    </div>
                </div>
                <div class="navbar navbar-expand-lg navbar-light navbar-stuck-menu mt-n2 pt-0 pb-2">
                    <div class="container">
                        <div class="collapse navbar-collapse" id="navbarCollapse">
                            <div class="input-group d-lg-none my-3">
                                <i class="ci-search position-absolute top-50 start-0 translate-middle-y text-muted fs-base ms-3"></i>
                                <input class="form-control rounded-start" type="text" placeholder="Tìm kiếm" />
                            </div>
                            <ul class="navbar-nav">
                                <li class="nav-item">


                                    <a class="nav-link ps-lg-0" asp-area="" asp-controller="Home" asp-action="Index">
                                        <i class="ci-home me-2"></i>Trang chủ
                                    </a>
                                </li>
                            </ul>
                            <ul class="navbar-nav">
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" asp-area="" asp-controller="SanPham" asp-action="Index" data-bs-toggle="dropdown" data-bs-auto-close="outside"><i class="ci-gift me-2"></i>Sản phẩm</a>
                                    <ul class="dropdown-menu">
                                        <li><a class="dropdown-item" asp-area="" asp-controller="SanPham" asp-action="PhanLoai" asp-route-tenLoai="ao-thun">Áo thun</a></li>
                                        <li><a class="dropdown-item" asp-area="" asp-controller="SanPham" asp-action="PhanLoai" asp-route-tenLoai="ao-so-mi">Áo sơ mi</a></li>
                                        <li><a class="dropdown-item" asp-area="" asp-controller="SanPham" asp-action="PhanLoai" asp-route-tenLoai="ao-polo">Áo polo</a></li>
                                        <li><a class="dropdown-item" asp-area="" asp-controller="SanPham" asp-action="PhanLoai" asp-route-tenLoai="ao-khoac">Áo khoác</a></li>
                                    </ul>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="BaiViet" asp-action="Index"><i class="ci-globe me-2"></i>Tin tức</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="BaiViet" asp-action="ChuDe" asp-route-tenChuDe="tuyen-dung"><i class="ci-loudspeaker me-2"></i>Tuyển dụng</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="LienHe" asp-action="Index"><i class="ci-support me-2"></i>Liên hệ</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </header>

        @RenderBody()
    </main>

    <footer class="footer bg-dark">
        <div class="pt-5 bg-darker">
            <div class="container">
                <div class="row pb-2">
                    <div class="col-md-6 text-center text-md-start mb-4">
                        <div class="text-nowrap mb-4">
                            <a class="d-inline-block align-middle mt-n1 me-3" href="#"><img class="d-block" src="~/img/footer-logo-light.png" width="117" /></a>
                        </div>
                        <div class="widget widget-links widget-light">
                            <ul class="widget-list d-flex flex-wrap justify-content-center justify-content-md-start">
                                <li class="widget-list-item me-4"><a class="widget-list-link" asp-area="" asp-controller="Home" asp-action="Index">Trang chủ</a></li>
                                <li class="widget-list-item me-4"><a class="widget-list-link" asp-area="" asp-controller="SanPham" asp-action="Index">Sản phẩm</a></li>
                                <li class="widget-list-item me-4"><a class="widget-list-link" asp-area="" asp-controller="BaiViet" asp-action="Index">Tin tức</a></li>
                                <li class="widget-list-item me-4"><a class="widget-list-link" asp-area="" asp-controller="BaiViet" asp-action="ChuDe" asp-route-tenChuDe="tuyen-dung">Tuyển dụng</a></li>
                                <li class="widget-list-item me-4"><a class="widget-list-link" asp-area="" asp-controller="LienHe" asp-action="Index">Liên hệ</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-6 text-center text-md-end mb-4">
                        <div class="mb-3">
                            <a class="btn-social bs-light bs-twitter ms-2 mb-2" href="#"><i class="ci-twitter"></i></a>
                            <a class="btn-social bs-light bs-facebook ms-2 mb-2" href="#"><i class="ci-facebook"></i></a>
                            <a class="btn-social bs-light bs-instagram ms-2 mb-2" href="#"><i class="ci-instagram"></i></a>
                            <a class="btn-social bs-light bs-pinterest ms-2 mb-2" href="#"><i class="ci-pinterest"></i></a>
                            <a class="btn-social bs-light bs-youtube ms-2 mb-2" href="#"><i class="ci-youtube"></i></a>
                        </div>
                    </div>
                </div>
                <div class="pb-4 fs-xs text-light opacity-50 text-center text-md-start">Bản quyền © 2024 bởi Nhom02</div>
            </div>
        </div>
    </footer>

    <a class="btn-scroll-top" href="#top" data-scroll>
        <span class="btn-scroll-top-tooltip text-muted fs-sm me-2">Top</span>
        <i class="btn-scroll-top-icon ci-arrow-up"></i>
    </a>

    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/vendor/bootstrap/bootstrap.bundle.min.js"></script>


    <script src="~/vendor/simplebar/simplebar.min.js"></script>
    <script src="~/vendor/tiny-slider/tiny-slider.js"></script>
    <script src="~/vendor/smooth-scroll/smooth-scroll.polyfills.min.js"></script>
    <script src="~/vendor/nouislider/nouislider.min.js"></script>
    <script src="~/vendor/imagesloaded/imagesloaded.pkgd.min.js"></script>
    <script src="~/vendor/shufflejs/shuffle.min.js"></script>
    <script src="~/vendor/lightgallery/lightgallery.min.js"></script>
    <script src="~/vendor/lightgallery/plugins/fullscreen/lg-fullscreen.min.js"></script>
    <script src="~/vendor/lightgallery/plugins/zoom/lg-zoom.min.js"></script>
    <script src="~/vendor/lightgallery/plugins/video/lg-video.min.js"></script>
    <script src="~/vendor/drift-zoom/Drift.min.js"></script>
    <script src="~/js/theme.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>